In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv(r'online_shoppers_intention.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), object(2)
memory usage: 1.5+ MB

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [3]:
missing_values = df.isnull().sum()
print(missing_values)

print("Total missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64
Total missing values: 0
Duplicate rows: 125

In [4]:
df = df.drop_duplicates()

In [5]:
df['Weekend'] = df['Weekend'].astype(int)
df['Revenue'] = df['Revenue'].astype(int)

In [6]:
month_map = {'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'June': 6, 
             'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12}
df['Month'] = df['Month'].map(month_map)

In [7]:
df = pd.get_dummies(df, columns=['VisitorType'], drop_first=True)

In [8]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 12205 entries, 0 to 12329
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Administrative                 12205 non-null  int64
 1   Administrative_Duration        12205 non-null  float64
 2   Informational                  12205 non-null  int64
 3   Informational_Duration         12205 non-null  float64
 4   ProductRelated                 12205 non-null  int64
 5   ProductRelated_Duration        12205 non-null  float64
 6   BounceRates                    12205 non-null  float64
 7   ExitRates                      12205 non-null  float64
 8   PageValues                     12205 non-null  float64
 9   SpecialDay                     12205 non-null  float64
 10  Month                          12205 non-null  int64
 11  OperatingSystems               12205 non-null  int64
 12  Browser                        12205 non-null  int64
 13  Region                         12205 non-null  int64
 14  TrafficType                    12205 non-null  int64
 15  Weekend                        12205 non-null  int64
 16  Revenue                        12205 non-null  int64
 17  VisitorType_Other              12205 non-null  bool
 18  VisitorType_Returning_Visitor  12205 non-null  bool
dtypes: bool(2), float64(7), int64(10)
memory usage: 1.7 MB

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,Weekend,Revenue,VisitorType_Other,VisitorType_Returning_Visitor
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,2,1,1,1,1,0,0,False,True
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,2,2,2,1,2,0,0,False,True
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,2,4,1,9,3,0,0,False,True
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,2,3,2,2,4,0,0,False,True
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,2,3,3,1,4,1,0,False,True

In [9]:
df.keys

<bound method NDFrame.keys of        Administrative  Administrative_Duration  Informational  \
0                   0                      0.0              0
1                   0                      0.0              0
2                   0                      0.0              0
3                   0                      0.0              0
4                   0                      0.0              0
...               ...                      ...            ...
12325               3                    145.0              0
12326               0                      0.0              0
12327               0                      0.0              0
12328               4                     75.0              0
12329               0                      0.0              0

       Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                         0.0               1                 0.000000
1                         0.0               2                64.000000
2                         0.0               1                 0.000000
3                         0.0               2                 2.666667
4                         0.0              10               627.500000
...                       ...             ...                      ...
12325                     0.0              53              1783.791667
12326                     0.0               5               465.750000
12327                     0.0               6               184.250000
12328                     0.0              15               346.000000
12329                     0.0               3                21.250000

       BounceRates  ExitRates  PageValues  SpecialDay  Month  \
0         0.200000   0.200000    0.000000         0.0      2
1         0.000000   0.100000    0.000000         0.0      2
2         0.200000   0.200000    0.000000         0.0      2
3         0.050000   0.140000    0.000000         0.0      2
4         0.020000   0.050000    0.000000         0.0      2
...            ...        ...         ...         ...    ...
12325     0.007143   0.029031   12.241717         0.0     12
12326     0.000000   0.021333    0.000000         0.0     11
12327     0.083333   0.086667    0.000000         0.0     11
12328     0.000000   0.021053    0.000000         0.0     11
12329     0.000000   0.066667    0.000000         0.0     11

       OperatingSystems  Browser  Region  TrafficType  Weekend  Revenue  \
0                     1        1       1            1        0        0
1                     2        2       1            2        0        0
2                     4        1       9            3        0        0
3                     3        2       2            4        0        0
4                     3        3       1            4        1        0
...                 ...      ...     ...          ...      ...      ...
12325                 4        6       1            1        1        0
12326                 3        2       1            8        1        0
12327                 3        2       1           13        1        0
12328                 2        2       3           11        0        0
12329                 3        2       1            2        1        0

       VisitorType_Other  VisitorType_Returning_Visitor
0                  False                           True
1                  False                           True
2                  False                           True
3                  False                           True
4                  False                           True
...                  ...                            ...
12325              False                           True
12326              False                           True
12327              False                           True
12328              False                           True
12329              False                          False

[12205 rows x 19 columns]>